# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "httparty", "~> 0.20.0"

gem "json", "~> 2.6"

gem "aws-sdk-s3", "~> 1.114"

gem "image_processing", "~> 1.12"
